[package]
name = "bevy_enoki"
version = "0.4.0"
edition = "2021"
authors = ["Lorenz Mielke"]
description = "2D Particle system plugin, that works well on wasm and mobile"
keywords = ["bevy", "particles", "shader", "2d", "particle"]
repository = "https://github.com/Lommix/bevy_enoki"
license = "MIT"
readme = "README.md"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[features]
dev = [
  "bevy/file_watcher",
  "bevy/dynamic_linking",
  "bevy/multi_threaded",
  "bevy/embedded_watcher",
]

[dependencies]
bevy = { version = "0.16.0-rc.1", default-features = false, features = [
  "bevy_core_pipeline",
  "bevy_asset",
  "bevy_sprite",
  "serialize",
  "png",
] }
serde = { version = "1.0.197", features = ["derive"] }
rand = "0.8.5"
ron = "0.8.1"
